### PR TITLE
Js2

### PR DESCRIPTION
**Pull request by Melisa-Zorraindo**
I'd appreciate feedback on:

- errors/bugs/non-working functionality. All unintentional, so please report.

- any ways I could make my code cleaner or organise it more efficiently.

- any other feedback you have to improve user experience.

### CODE REVIEW

**Comment by Fermain** [comment]
Minor Bug - `` tag is created for a post, even if the post has no `media`

**Comment by Fermain** [comment]
Query - Profile image is hardcoded. I expected this to be using my profile `avatar`

**Comment by Fermain** [comment]
UX - Reaction picker should send when you select an item, not on enter.

**Comment by Fermain** [comment]
Theme - Body with `min-vh-100 d-flex flex-column` allows you to keep the body full height at all times.

**Comment by Fermain** [comment]
Based on an `End-to-End` manual test run in a browser, it seems that you have met the brief well and do not need to make any major changes to pass this assignment. I will now begin your code review to suggest ways to improve, you can find my code suggestions in the `teacher-review` branch.

**Comment by Fermain** [comment]
No major issues from your code review either. I have added some comments and suggestions to the branch. The biggest challenge you face is large complicated files. It would be great to break these files up by using import/export so that the page setup files only contain a small number of functions to make the behaviour very clear. Check out my example for a hint on the direction.

This submission shows a really good level of research, application and understanding.

**Review by Fermain — APPROVED** [review]
This submission would benefit from refactoring large files, but the code quality is good and the required features are present. The site is attractive and has a good user experience in most cases. Improvements to be made relate to code organisation and UX rather than core functionality.

**Comment by Melisa-Zorraindo** [comment]
> min-vh-100 d-flex flex-column

fixed

**Comment by Melisa-Zorraindo** [comment]
> Query - Profile image is hardcoded. I expected this to be using my profile `avatar`

fixed

**Comment by Melisa-Zorraindo** [comment]
> Minor Bug - `` tag is created for a post, even if the post has no `media`

fixed

**Comment by Melisa-Zorraindo** [comment]
> UX - Reaction picker should send when you select an item, not on enter.

fixed

**Pull request merged**
